include $(GENERIC_X86_CONFIG_MK)
TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_USES_TSLIB := false
BOARD_WPA_SUPPLICANT_DRIVER :=
BUILD_EMULATOR_OPENGL:=true
TARGET_ARCH_VARIANT := x86
TARGET_ARCH := x86
BOARD_KERNEL_CMDLINE += SDCARD=sda
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1024M
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
TARGET_NO_KERNEL := false
BOARD_KERNEL_CMDLINE := init=/init console=ttyS0,115200 console=tty0 androidboot.hardware=vbox86 androidboot.console=ttyS0

